### ISSUE TITLE
Build error, in MacOS

### ISSUE THREAD

**Issue by stormrise** [Tomotoes/scrcpy-gui#5]
## Issue Type
Build error, in MacOS
请帮忙看看，谢谢

## scrcpy-gui Related Information
    ERROR in Template execution failed: ReferenceError: process is not defined
    
    ERROR in   ReferenceError: process is not defined
      
      - index.ejs:771 
        /Users/user/Documents/GitHub/scrcpy-gui/src/index.ejs:771:2
      
      - index.ejs:776 module.exports
        /Users/user/Documents/GitHub/scrcpy-gui/src/index.ejs:776:3
      
      - index.js:284 
        [scrcpy-gui]/[html-webpack-plugin]/index.js:284:18

**Comment by Tomotoes** [comment]
我已更新了 针对此问题的打包配置, 您可以再重新下载项目 试试~

**Comment by stormrise** [comment]
👌，重新pull了之后打包， 新的错误，大佬能帮忙看一下么，npm新手

 • signing         file=build/mac/ScrcpyGui.app identityName=Mac Developer: stormrise0414@hotmail.com (3SM8GDDPRR) identityHash=4D940548B7E04D4F581AA13705CF4BB466AD8836 provisioningProfile=none
Error: Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache /Users/stormrise/Documents/GitHub/scrcpy-gui/build/mac/ScrcpyGui.app
/Users/stormrise/Documents/GitHub/scrcpy-gui/build/mac/ScrcpyGui.app: rejected

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
From previous event:
    at MacPackager.sign (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/macPackager.ts:122:97)
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/macPackager.ts:317:21
    at go$readdir$cb (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/graceful-fs/graceful-fs.js:187:14)
    at FSReqCallback.oncomplete (fs.js:153:23)
From previous event:
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/macPackager.ts:315:27
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.signApp (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/macPackager.ts:312:73)
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at MacPackager.doPack (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/macPackager.ts:90:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/macPackager.ts:82:95)
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at callback (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:166:5)
From previous event:
    at Packager.doBuild (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/graceful-fs/graceful-fs.js:136:16
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:153:23)
From previous event:
    at Packager._build (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Packager.build (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/electron-builder/src/builder.ts:228:10)
    at /Users/stormrise/Documents/GitHub/scrcpy-gui/node_modules/electron-builder/src/cli/cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrcpy-gui@1.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrcpy-gui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by stormrise** [comment]
噗，还是说我没有权限去sign，我发现打包出来了

**Comment by Tomotoes** [comment]
谢谢~ 打包后的程序可以正常运行吗?

**Comment by stormrise** [comment]
待我一会测试一下，如果可以的话，发你邮箱

**Comment by Tomotoes** [comment]
嗯嗯 谢谢 , 就怕存在 一些打包配置问题.. 等你好消息





------------------------------------------------------------------
发件人：stormrise <notifications@github.com>
发送时间：2019年9月10日(星期二) 21:10
收件人：Tomotoes/scrcpy-gui <scrcpy-gui@noreply.github.com>
抄　送：Simon <simon@tomotoes.com>; Comment <comment@noreply.github.com>
主　题：Re: [Tomotoes/scrcpy-gui] Build error, in MacOS (#5)

待我一会测试一下，如果可以的话，发你邮箱

**Comment by stormrise** [comment]
<img width="311" alt="Screen Shot 2019-09-10 at 9 19 54 PM" src="https://user-images.githubusercontent.com/24603395/64617296-cb7c5880-d410-11e9-8a5f-e00bfd392d75.png">
首先发现了一个BUG，这个图标拉伸得巨大，
然后还是有点问题，用的miui，但是直接adb connect能行，mirror不行，暂时没有找到是何种原因

**Comment by Tomotoes** [comment]
啊...

**Comment by stormrise** [comment]
plus，这个退出好像有点问题

**Comment by stormrise** [comment]
<img width="732" alt="Screen Shot 2019-09-10 at 9 53 30 PM" src="https://user-images.githubusercontent.com/24603395/64619902-7727a780-d415-11e9-9cf1-a646a285fbb7.png">
maybe是这个原因？

···
2019-09-10 21:52:17.127 scrcpy[88809:20729511] INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: device offline
2019-09-10 21:52:17.133 scrcpy[88809:20729511] ERROR: "adb push" returned with value 1
···

**Comment by Tomotoes** [comment]
可能是创建进程在 macos 上 有权限问题

**Comment by skyeryg** [comment]
`src/main/scrcpy/index.js` 51行修改为
```const scrcpy = spawn('scrcpy', [...args, '-s', `${id}`])```
