### ISSUE TITLE
build的时候出错

### ISSUE THREAD

**Issue by canronglan** [Tomotoes/scrcpy-gui#98]
编译的时候出错了
c:\scrcpy-gui-1.5.1>npm run build

> scrcpy-gui@1.5.1 build c:\scrcpy-gui-1.5.1
> node .electron-vue/build.js && electron-builder

internal/modules/cjs/loader.js:965
  throw err;
  ^

**Error: Cannot find module 'webpack/lib/RuleSet'**
Require stack:
- c:\scrcpy-gui-1.5.1\node_modules\vue-loader\lib\plugin.js
- c:\scrcpy-gui-1.5.1\node_modules\vue-loader\lib\index.js
- c:\scrcpy-gui-1.5.1\.electron-vue\webpack.renderer.config.js
- c:\scrcpy-gui-1.5.1\.electron-vue\build.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:838:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1022:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (c:\scrcpy-gui-1.5.1\node_modules\[4mvue-loader[24m\lib\plugin.js:2:17)
[90m    at Module._compile (internal/modules/cjs/loader.js:1118:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:982:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:875:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1022:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'c:\\scrcpy-gui-1.5.1\\node_modules\\vue-loader\\lib\\plugin.js'[39m,
    [32m'c:\\scrcpy-gui-1.5.1\\node_modules\\vue-loader\\lib\\index.js'[39m,
    [32m'c:\\scrcpy-gui-1.5.1\\.electron-vue\\webpack.renderer.config.js'[39m,
    [32m'c:\\scrcpy-gui-1.5.1\\.electron-vue\\build.js'[39m
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrcpy-gui@1.5.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrcpy-gui@1.5.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by canronglan** [comment]
最后发现用yarn install 就可以解决，关闭了~
